### ISSUE TITLE
tags not removed

### ISSUE THREAD

**Issue by jonimant** [modxcms/Articles#97]
Removing tags not working in the articles before the buttons was a cross
and now only add button. Modx v. 2.3.1.

**Comment by watou** [comment]
+1. Can confirm 2.3.1 wanting to remove tags on an existing article and are only presented do-nothing buttons -- no remove functionality.

**Comment by bennyb** [comment]
Yeah also have this issue.

**Comment by mazuhl** [comment]
+1 on this issue

Quick fix for anyone (@jonimant, @watou, @bennyb) needing to get this resolved before the next release, add the following CSS to your `manager/templates/default/index.css` file (and refresh your browser):

``` css
.x-superboxselect-item-close:after {
  margin-left: 3px;
  content: 'x';
  color: black;
}
```
